### ISSUE TITLE
What change you do in formatted.csv?

### ISSUE THREAD

**Issue by abdulrehmanch** [AsadRasheed-AR/Excel-to-HTML-Python-script#1]
Please explain what changes you do in the formated csv. I found some encoding error.

![image](https://user-images.githubusercontent.com/11248333/117938932-fecb6500-b320-11eb-8023-f0d3a7761903.png)

**Comment by AsadRasheed-AR** [comment]
I did not make any changes in the encoding, I am attaching a screenshot which contains original file on left and modified one on right and you can see both files have the same characters without any encoding, Please open the files in MS Excel and then you should not see any difference in both files related to encoding. Attaching a picture below for your reference.

NOTE : Left Image contains original file , Right image contains formatted/modified file.
![encoding](https://user-images.githubusercontent.com/68403761/118135387-674b3c80-b41c-11eb-97ab-940172601a7e.JPG)

However I made some changes related to formatting, Attaching a screenshot below for your reference.
NOTE : Left Image contains original file , Right image contains formatted/modified file.
Some formatting differences are given below:

1- On row 24 (row 23 in formatted file due to deletion of an empty row), I removed character 'a' because as per the requirements, the class column should only contain numbers (digits) and decimal points (.)
2- On row 28 in original file, I deleted this row because this row contains decimal point which are causing problem in class detection algorithm which works on decimal points to detect class (RowClass) For example : 2.1.1 contains 2 decimal points so as per the requirement it should belongs to "RowClass3".
3- Row 40 in original file , I shifted this row to below row 41 (row numbers may be different in formatted file). The reason for shifting this row is because it will discontinue the nested list. There are two rules , If it belongs to list then it should contain some class indication such as (12.1) to be a part of the list, or if it is a heading then it should be before the list. 
"Note : There should be no heading between list items, because it will discontinue the list, The heading should be before the starting of the list".
4-On row 43,  I shifted "ResursStatus" from column B to Column A, I am assuming that it is a heading so the headings and the class indication should be in the first column only. There should be no other thing in the first column other than heading or class indication.

Format for the file should be.

heading
x  (list start contains plus sign)
x.x (list item one)
x.x (list item two with plus sign because it contains one child)
x.x.x (child of list item two)

*** Compare the file "LstMetadataprofiltest_formatted" with the orignal file you sent to me "LstMetadataprofilCopy" and you will find the differences that I made to make the format consistent. you can test the script with any other file But the format of the file must be same *** 
![formatting](https://user-images.githubusercontent.com/68403761/118137752-feb18f00-b41e-11eb-950f-d2a85ebceab0.JPG)
